### ISSUE TITLE
Create Account for Automated Onboard system

### ISSUE THREAD

**Issue by ModalHydra** [UTDallasEPICS/Warren-Automated-Onboard#21]
This issue involves using the create account page of the application to add a new email and password to the employee table in the Onboarding systems database. The create account page must accept a username/email and password as input, verify that the input is valid, send that input to the database where a new table entry is created, and return the user to the sign in page, where they can try to sign in

**Comment by MStolen** [comment]
With the implementation of #32, account creation will no longer be needed.
