### ISSUE TITLE
[Question] Add the list of tasks to Automated-Onboarding system

### ISSUE THREAD

**Issue by ModalHydra** [UTDallasEPICS/Warren-Automated-Onboard#22]
Look over the list of tasks provided in the excel sheet and manually add them to the home page of the web application as well as a new task table in the Onboarding database. each task should have a name, description, indicator of completion, due date,  and button to confirm task completion.

**Comment by TusharW4ni** [comment]
Will need to ask Brandy, how exactly she wants this to be done.

**Comment by TusharW4ni** [comment]
Asked Brandy yesterday and she said to just include the description of the task, completion button, date completed, and the supervisor assigned to that task. 

For the Basic Onboarding department, she wants there to be a "category" of Pre-Hire and First Day. The tasks for the respective categories will be listed below these headings. 

These tasks are listed in the New Hire Checklist excel document in the Box folder called 2022 Fall. Here's a link to the excel (however I don't know if this will directly work for everyone on the team. Probably not, so will have to go to the Box folder manually.): https://utdallas.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1026553828815&sharedAccessCode=
