### ISSUE TITLE
Supervisor account feature for Automated Onboarding system

### ISSUE THREAD

**Issue by ModalHydra** [UTDallasEPICS/Warren-Automated-Onboard#24]
Have a separate view of the application based on if the user is marked as a regular employee or supervisor. when an account is created, an option of making that account a supervisor needs to be added. when the employee signs in, a request should be made to the database to confirm if they are a supervisor or not, if they are a supervisor, they should go to supervisor_home, and if they are an employee, they should go to regular_home. remove the confirm completion button from the regular home and add the buttons to supervisor_home.

**Comment by MStolen** [comment]
This will need to be combined with #32 using a table in the database to define user roles.

**Comment by MStolen** [comment]
Also look at #20 for more detail as well

**Comment by TusharW4ni** [comment]
Since supervisor view will be extremely similar to admin view except the edit buttons, it will be not too difficult to implement. It will be probably pushed to next semester. Also the use case described by ModalHydra is very different from what we have right now, so this has become irrelevant.
