### ISSUE TITLE
[Feature] Authentication - Auth0 (Microsoft Login)

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Warren-Automated-Onboard#32]
- get rid of the password implementation, look into integrating with office/gsuite/whatever enterprise stuff warren has
- this makes it straightforward to onboard employees into the system

**Comment by TusharW4ni** [comment]
they use office 365

**Comment by MStolen** [comment]
Looks like [this auth0 integration](https://marketplace.auth0.com/integrations/office-365-sso) will work with their current setup.

**Comment by MStolen** [comment]
#20 has more information on this, but I have closed it since this is the same thing.

**Comment by TusharW4ni** [comment]
**Feature Description**
Make the login screen which links to Auth0. From Auth0 use the login info passed from Microsoft to check against our database. If the email is available let them into their correct page.

Another idea might be: if the email doesn't exist, make a new employee user in the database.
