### ISSUE TITLE
[Feature] Departments Page

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Warren-Automated-Onboard#33]
- department table
- management UI - CRUD

**Comment by TusharW4ni** [comment]
**Feature Description**
This page will be very similar to what the Users Page is currently.

**Requirements**
* Table of departments listed
* Columns of the table, right now, look like this: Names, # of Tasks, # of Employees
* Upon clicking a row, it will expand to show the task list of that department
* All the buttons and layout and search bar will be exactly like the users' page
