### ISSUE TITLE
Unfulfilled Requirements

### ISSUE THREAD

**Issue by ssamikshaa** [UTDallasEPICS/Warren-Automated-Onboard#55]
### **To be completed:**
- Admin View:
   - complete archive department functionality & view archived departments on the archive page
   - fix search bar on users page to include filtering by onboarding employee's name
   - fix edit user to remove unnecessary mappings after changing role or department
- Supervisor View:
   - sort list of users under a task by id to prevent resorting user order after checking off tasks
- Employee View: 
   - fix search bar to sort based on task description
   - add pagination for list of tasks

**Comment by TusharW4ni** [comment]
okay lets make these separate issues and tackle them one by one.
