### ISSUE TITLE
[BUG] Fix mappings after changing supervisor role

### ISSUE THREAD

**Issue by ssamikshaa** [UTDallasEPICS/Warren-Automated-Onboard#56]
In edit user, changing from supervisor to any other role does not remove the supervisorTaskMappings. In the frontend, the task table still shows the user to be assigned to the task.

Before changing roles from supervisor, make check to see if they still have tasks assigned to them. If they do, then prompt them to reassign tasks before changing user role.

**Comment by ssamikshaa** [comment]
Remove supervisor archive page since there will be no tasks that are assigned to them any longer.

**Comment by TusharW4ni** [comment]
Now supervisors and admins are not allowed to change their roles. The user will need to delete the user if they wanted them to have another role. Now, if you delete a supervisor the user will also need to reassign their task mappings before this is allowed.
