### ISSUE TITLE
[BUG] Change archive task button to delete task button

### ISSUE THREAD

**Issue by ssamikshaa** [UTDallasEPICS/Warren-Automated-Onboard#66]
The current archive task button deletes the task because tasks themselves cannot be archived, only their mappings. Change the archive task button to a red delete task button to reflect its functionality. Rename the API calls in the backend to delete instead of archive.

**Comment by TusharW4ni** [comment]
implemented this in #57 
Deleting task now does not show up in the department, supervisors, and onboarding employees.
