### ISSUE TITLE
[BUG] Change archive department button to delete department

### ISSUE THREAD

**Issue by ssamikshaa** [UTDallasEPICS/Warren-Automated-Onboard#67]
For the first version, change the archive department button to delete department button. The delete button will only delete departments after confirming there are no users assigned to it. 

In the future, this will be changed back to implement the archive department feature.

**Comment by TusharW4ni** [comment]
implemented this in #57 
now it says that you can't delete when there are employees assigned to the department. Otherwise, user is allowed to delete. Its archived attribute is set to true in the backend when this happens.
